Método para adicionar data de saída, tirar o ativo e por o motivo para a saída do associado
marcosdosea/GestaoGrupoMusical pull request #138
Opened 2023-06-26 19:13 UTC by matheusmt12

2023-06-27 16:33 UTC, Gabrielx47 requested changes
O método Edit e RemoverAssociado (ambos estão presente no arquivo "PessoaService.cs") cumprem o mesmo papel, isto é, atualizam os dados de uma pessoa e salva as mudanças. Sendo assim, seria interessante fazer um ajuste.

## Solução
![O](https://github.com/marcosdosea/GestaoGrupoMusical/assets/62863349/633301d6-4554-43ae-9870-0ce512072d73)
Para mais detalhes clique [aqui](https://rules.sonarsource.com/csharp/RSPEC-4144).

2023-06-27 19:11 UTC, junio10 approved these changes
Metódo service e controller funcionando perfeitamente. parabéns @matheusmt12

2023-06-27 19:16 UTC, junio10 requested changes
conserta o que @Gabrielx47 falou acima

2023-06-27 20:56 UTC, matheusmt12 commented
Acho que você não entendeu o que foi feito na issue, ela n é para editar e sim para trocar o status do associado caso ele tenha saído, como não vai remover ele do banco o status ativo fica como inativo, o método de editar seria pra trocar informações do usuário, já esse método é pra deixar ele inativo do grupo @Gabrielx47

2023-06-28 13:59 UTC, reinan47 approved these changes
Resolução de conflito feita.

2023-06-28 18:18 UTC, junio10 approved these changes
Parabéns matheus ! conflito resolvido e codigo funcionando. Depois lembrar de colocar um input melhor para motivo da saída. resolve #133

2023-07-01 00:44 UTC, reinan47 commented
PessoaController
|---|
![Controller](https://github.com/marcosdosea/GestaoGrupoMusical/assets/91684220/20a4732b-09a1-4623-a00a-036ef4479f9f)
---
PessoaService
|---|
![Service](https://github.com/marcosdosea/GestaoGrupoMusical/assets/91684220/ea3bca5b-a729-48b3-ab89-d01eb3b7b0a8)

2023-07-03 13:54 UTC, merged