Remoção do campo "Status" da tela de edição de instrumento musical
marcosdosea/GestaoGrupoMusical pull request #141
Opened 2023-06-27 00:09 UTC by Gabrielx47

## Revisar:
- Verificar se o campo "Status" não está mais presente na view Edit do UC Instrumento Musical.

## Foto da tela após a alteração:
![image](https://github.com/marcosdosea/GestaoGrupoMusical/assets/62863349/b1c7f665-4af2-4f50-8bdf-76deac0d3ebd)

2023-06-28 01:25 UTC, lauro-ss submitted a review, later dismissed
Olá, @Gabrielx47 , ao realizar um update de um instrumento o mesmo não está sendo atualizado. Isso ocorre porque você removeu completamente o input status, logo, ele está indo como "null" ou "string vazia" para a controller e não está sendo validado. 

## Possível solução
- Adicionar um `<input type="hidden"  asp-for="Status" />`

2023-07-03 21:19 UTC, junio10 approved these changes
checkbox funcionando devidamente. resolve #125 .

2023-07-04 13:07 UTC, junio10 requested changes
Inverter o checkbox para danificado.

2023-07-04 17:26 UTC, ms-daniel requested changes
resolver novos conflitos

2023-07-04 21:34 UTC, junio10 approved these changes
Parabéns @Gabrielx47  e @reinan47

2023-07-04 21:36 UTC, ms-daniel approved these changes

2023-07-04 21:41 UTC, merged