Adicionado cadastro identity, envio de e-mail e estilo para Administrador Grupo
marcosdosea/GestaoGrupoMusical pull request #177
Opened 2023-07-07 20:08 UTC by lauro-ss

# O que foi feito
- Estilo seguindo o padrão digital do sistema
- Cadastro identity as novas e já existentes pessoas
- Envio via e-mail de login e senha do administrador do grupo
- Remoção de warnings de código

## Para testar
### Requisitos
- Ter no mínimo um Manequim registrado no banco
- Ter no mínimo um Grupo Musical registrado no banco
- Ter o Papel Grupo "Administrador Grupo" registrado no banco

### Script
```
INSERT INTO grupomusical VALUES(1, "Batalá - SE", "Batala Group", "22884507000198", "69309215",
                                "Travessa dos Imigrantes","Buritis", "Boa Vista", "RR" , "Brasil",
                                "batalateste@gmail.com", "/batalaRR", "@batalaRR", "/batalaRR", "(27) 2463-7172",
                                "(82) 2399-2069", "do Brasiiiil", "9999", "1739306-5", "394.464.570-76",  "CPF");

INSERT INTO papelgrupo VALUES (1, "ASSOCIADO"),
                              (2, "COLABORADOR"),
                              (3, "ADMINISTRADOR GRUPO"),
                              (4, "ADMINISTRADOR SISTEMA");
                              
INSERT INTO MANEQUIM VALUES (1,"PP","Extra Pequeno"),
			    (2,"P","Pequeno"),
                            (3,"M","MEDIO"),
                            (4,"G","Grande");
```
Obs: Se você já possui esses dados, basta apenas ir para o próximo tópico.

### Como testar
Após iniciar o sistema, clique em "Grupo Musical" no menu lateral esquerdo. Após carregar, clique em "Administradores" em qualquer Grupo Musical que desejar. Então, insira um CPF de alguma pessoa registrada ou insira um CPF novo para um novo cadastro. O campo e-mail deve ser um e-mail existente para que possa receber o e-mail com login e senha.

## Tela
![image](https://github.com/marcosdosea/GestaoGrupoMusical/assets/69280619/d6029a21-3a43-4ccd-b4de-c5c1b7cfe1b1)

## Exemplo de e-mail recebido
![image](https://github.com/marcosdosea/GestaoGrupoMusical/assets/69280619/35f6fd86-9c87-46a1-b6b5-cac48b9d4aac)

2023-07-08 08:32 UTC, reinan47 requested changes
A brach está conflituosa, resolva os conflitos e suba o arquivo novamente.

2023-07-09 00:50 UTC, reinan47 approved these changes

2023-07-09 00:52 UTC, reinan47 requested changes
PessoaService.cs conflitante

2023-07-10 16:31 UTC, junio10 approved these changes
### Funcionando perfeitamente o notificar e o adicionar adm
![image](https://github.com/marcosdosea/GestaoGrupoMusical/assets/50469065/67977dd2-1d6a-4198-ac6d-9e7a73e359eb)

2023-07-10 16:32 UTC, merged

2023-07-10 16:33 UTC, junio10 commented
resolve #161