Estilização de cadastro do associado
marcosdosea/GestaoGrupoMusical pull request #186
Opened 2023-07-09 17:39 UTC by reinan47

2023-07-10 17:43 UTC, lauro-ss requested changes
@reinan47 a tela está ótima, mas os títulos em baixo do título da página "Novo Associado" estão com um texto maior. Você utilizou h5 para o título "Novo Associado" e h3 para os demais. 
Minha sugestão:
Na linha 11 
de
`<h5 class="p-3 bg-danger  opacity-75 text-white">Novo Associado</h5>`
para
`<h1 class="p-3 bg-danger  bg-opacity-75 text-white fs-5">Novo Associado</h1>`

Isso irá manter a estrutura da página com o H1 existente, e irá manter o mesmo tamanho do H5. Recomendo utilizar o tamanho do H5 pois ficou muito bonito e combina com todas as telas. 

Para as outras linhas:
Linha 26
de
`<h3>Dados pessoais</h3>`
para
`<h2 class="fs-5">Dados pessoais</h2>`

Linha 131
de
`<h3>Endereço</h3>`
para
`<h2 class="fs-5">Endereço</h2>`

2023-07-11 00:20 UTC, reinan47 commented
classe mudada do site.css
|---|
Adição das linhas :     
    --bs-bg-opacity: 1;
    background-color: rgba(var(--bs-light-rgb), var(--bs-bg-opacity)) !important;
![form](https://github.com/marcosdosea/GestaoGrupoMusical/assets/91684220/e8d42df0-95ad-4bfc-be2d-50ed7832d108)

2023-07-11 00:37 UTC, reinan47 commented
Tela seguindo o padrão
|---|
![image](https://github.com/marcosdosea/GestaoGrupoMusical/assets/91684220/2ac9f922-0844-4ef4-824e-10ea6329cf16)

2023-07-13 18:03 UTC, matheusmt12 approved these changes

2023-07-13 18:05 UTC, matheusmt12 commented
@lauro-ss, @reinan47 já fez as alterações solicitadas, e como o resto do esta tudo certo, estarei dando Merge

2023-07-13 18:06 UTC, merged