Feita alteração no código para mostrar os instrumentos de um determinado grupo musical
marcosdosea/GestaoGrupoMusical pull request #282
Opened 2023-07-23 14:36 UTC by matheusmt12

**Oque foi feito:**

- > Alteração na assinatura do método GetAllDTO de instrumento musical agora esta passando o id do grupo nele

2023-07-23 19:21 UTC, ms-daniel commented
em revisão

2023-07-24 13:14 UTC, ms-daniel requested changes

2023-07-24 13:14 UTC, ms-daniel commented on Codigo/Service/InstrumentoMusicalService.cs
> +                               join grupo in _context.Grupomusicals on instrumento.IdGrupoMusical equals idGrupo join
ao invés de acrescentar mais uma tabela que possa deixar a consulta mais lenta/demorada, utilize o "where" antes do join e remova todo o join com grupo.

2023-07-24 18:25 UTC, matheusmt12 commented on Codigo/Service/InstrumentoMusicalService.cs
> +                               join grupo in _context.Grupomusicals on instrumento.IdGrupoMusical equals idGrupo join
Fiz essa alteração, por favor, revise e se possível me avise se era isso mesmo.

2023-07-24 23:06 UTC, ms-daniel approved these changes
otimo!

2023-07-24 23:06 UTC, merged