Tela de Instrumentos Musicais - Delete
marcosdosea/GestaoGrupoMusical pull request #292
Opened 2023-07-24 23:35 UTC by Gabrielx47

### Revisar
- verificar o *código* da  *view Delete* do caso de uso *Instrumento Musical*.
- verificar a *mudança no nome usado para representar o atributo Status* nas views de *Instrumento Musical*. O nome usado era "Disponível" e passou a ser "Status".

### Resultado final:
![image](https://github.com/marcosdosea/GestaoGrupoMusical/assets/62863349/8aa0c5db-4ef0-41d3-a642-35674ea4602d)

2023-07-25 00:44 UTC, ms-daniel requested changes
Seguir padrão da view de details que foi implementada em Grupo Musical

2023-07-26 15:00 UTC, ms-daniel requested changes
# Correções:
- [x] Alinhar colunas
- [ ] Remover Id e IdGrupoMusical da tela apresentada
- [ ] Data de aquisição não está aparecendo no campo
- [ ] No campo "Instrumento" precisa aparecer o nome do instrumento e não o Id

2023-07-28 10:47 UTC, Gabrielx47 commented
@ms-daniel Mudanças realizadas.

2023-07-28 18:00 UTC, ms-daniel requested changes
Correções:
- [ ] Resolver conflitos
- [ ] Corrigir margem dos botões de Voltar e Excluir (Ver Editar)

2023-07-28 20:08 UTC, ms-daniel requested changes
Remover mudanças no arquivo dentro do projeto EMAIL..

2023-07-28 20:08 UTC, ms-daniel commented on Codigo/Email/Template/EmailResource.Designer.cs
remover este arquivo das mudanças

2023-07-29 00:44 UTC, ms-daniel approved these changes
P E R F E I T O.

2023-07-29 00:44 UTC, merged