Branch reinan315
marcosdosea/GestaoGrupoMusical pull request #319
Opened 2023-07-27 02:32 UTC by reinan47

<div align="center">
  <img src="https://github.com/marcosdosea/GestaoGrupoMusical/assets/62726040/26118ce6-8a10-4f3a-b8a3-c3b90851b04b" width="10%">
  <h1>Pull Request</h1> 
</div>

## Foi Solicitado
Validação do CPF para as views de grupo mujsical quando o atributo que define a chave pix for setado.

## Foi Feito
[Explique as alterações realizadas neste Pull Request de forma detalhada. Use o checklist markdown como o exemplo abaixo]
- [x] Adição do codigo JS com validação de CPF
- [x] Adição da Validação do CPF no input da Chave pix

## Como Testar
Só é adicionar o tipo da chave pix de CPF e testar com CPF válido e outro inválido

**Certifique-se de revisar o código e testar as alterações localmente antes de solicitar/fazer o merge.**

2023-07-28 11:23 UTC, Gabrielx47 commented
Estou revisando esta pr.

2023-07-28 11:49 UTC, Gabrielx47 requested changes
## Corrigi:
-[ ] Validação dos CPF não estão funcionando corretamente. Ao colocar um CPF inválido  e clicar no botão **Editar** ou no **Adicionar**  o sistema informa a invalidade do mesmo, porém, ao clicar uma segunda vez os dados são salvos. Sendo assim, é necessário corrigir essa situação.
- [x] Os campos que apenas tem número como input não deveria permitir a escrita de qual outro tipo de caractere. Isto deveria ser aplicado no Create e no Edit.

2023-07-28 20:57 UTC, reinan47 commented
Minha PR é pra revisar o cpf, essa solicitações cadastrar no backlog.

2023-07-29 00:50 UTC, Gabrielx47 approved these changes
O código está funcionando corretamente. Dessa forma, aprovarei as mudanças.

2023-07-29 00:52 UTC, merged