Branch gabriel306
marcosdosea/GestaoGrupoMusical pull request #320
Opened 2023-07-27 07:22 UTC by Gabrielx47

<div align="center">
  <img src="https://github.com/marcosdosea/GestaoGrupoMusical/assets/62726040/26118ce6-8a10-4f3a-b8a3-c3b90851b04b" width="10%">
  <h1>Pull Request</h1> 
</div>

## Foi Solicitado
- Ajustes no botões e  colocar os campos da view Details um ao lado do outro.

## Foi Feito
[Explique as alterações realizadas neste Pull Request de forma detalhada. Use o checklist markdown como o exemplo abaixo]
- [x] Ajustes nos botões "Voltar" e "Editar".
- [x] Colocar os campos de Redes Sociais um ao lado do outro.

## Mudanças Que Não Estavam Previstas

## Como Testar
[Forneça instruções claras sobre como testar as alterações feitas neste Pull Request. Inclua comandos, configurações ou procedimentos necessários.]
Apenas faça login como administrador do sistema e acesse a view de 
Grupo Musical. Depois  escolha um grupo musical e clique em Detalhes. Chegando lá verifique os items listados acima e também como a página reagi de maneira responsiva.

## Prints
![image](https://github.com/marcosdosea/GestaoGrupoMusical/assets/62863349/f764d738-63e9-453e-af3b-654962376f61)

**Certifique-se de revisar o código e testar as alterações localmente antes de solicitar/fazer o merge.**

2023-07-27 15:05 UTC, ms-daniel requested changes
deixar email em uma row sozinho

2023-07-28 10:46 UTC, Gabrielx47 commented
@ms-daniel  Mudanças realizadas.

2023-07-28 18:10 UTC, ms-daniel requested changes
Não consigo ver as mudanças aqui:

## Chrome
![image](https://github.com/marcosdosea/GestaoGrupoMusical/assets/62726040/6a426f92-e440-4b5b-b29c-84840af9e04a)

# Brave
![image](https://github.com/marcosdosea/GestaoGrupoMusical/assets/62726040/93692859-2ac4-4a35-b3d3-631b92dcc8b7)

2023-07-28 18:10 UTC, ms-daniel commented on Codigo/Email/Template/EmailResource.Designer.cs
Desfazer esta mudança

2023-07-28 19:48 UTC, Gabrielx47 commented on Codigo/Email/Template/EmailResource.Designer.cs
Ei, aqui está funcionando perfeitamente. Evidente que em um certa quantidade de pixel os campos fiquem um abaixo do outro.
![image](https://github.com/marcosdosea/GestaoGrupoMusical/assets/62863349/665dbf7e-29f8-4d43-89f3-129a6e735c93)

2023-07-28 20:11 UTC, ms-daniel requested changes
Remover alterações dentro do arquivo EmailResource.Designer.cs

2023-07-29 00:45 UTC, ms-daniel approved these changes
Ó T I M O.

2023-07-29 00:45 UTC, merged