Resolução do bug de figurino com CheckBox de Danificado marcado
marcosdosea/GestaoGrupoMusical pull request #393
Opened 2023-08-10 21:53 UTC by matheusmt12

<div align="center">
  <img src="https://github.com/marcosdosea/GestaoGrupoMusical/assets/62726040/26118ce6-8a10-4f3a-b8a3-c3b90851b04b" width="10%">
  <h1>Pull Request</h1> 
</div>

## Foi Solicitado
Resolver bug

**Certifique-se de revisar o código e testar as alterações localmente antes de solicitar/fazer o merge.**

2023-08-10 23:33 UTC, reinan47 requested changes
Seja mais claro na descrição da issue para saber de qual bug se trata...

2023-08-10 23:51 UTC, ms-daniel requested changes
Deixar indentação anterior para visualizar a mudança que foi feita

2023-08-11 00:00 UTC, reinan47 approved these changes
Revisado, Parabéns Matheus

2023-08-11 12:18 UTC, matheusmt12 commented
@ms-daniel a linha que foi adicionada foi a linha 113, o resto do código é o mesmo.
 Linha: "$('#Danificado').prop('checked', false);"

2023-08-11 14:01 UTC, ms-daniel requested changes
Está com um TAB a mais que o necessário no arquivo

2023-08-11 14:03 UTC, ms-daniel approved these changes

2023-08-11 14:03 UTC, merged