Details - Design System - Ensaio
marcosdosea/GestaoGrupoMusical pull request #395
Opened 2023-08-11 09:27 UTC by Gabrielx47

<div align="center">
  <img src="https://github.com/marcosdosea/GestaoGrupoMusical/assets/62726040/26118ce6-8a10-4f3a-b8a3-c3b90851b04b" width="10%">
  <h1>Pull Request</h1> 
</div>

## Foi Solicitado
Colocar a view Details no padrão de estilização usado no sistema.

## Foi Feito
[Explique as alterações realizadas neste Pull Request de forma detalhada. Use o checklist markdown como o exemplo abaixo]
- [x] A view Details foi padornizada conforme o design system do sistema. 

## Mudanças Que Não Estavam Previstas
- [x] Criação de um DTO (EnsaioDetailsDTO).
- [x] Criação de um método para pegar os dados do ensaio (o nome do método é GetDetailsDTO).
- [x] Uso da DTO EnsaioDetailsDTO na view Details.

## Como Testar
Faça login no sistema como Administrador do Grupo e acesse a página referente a ensaio. Chegando lá clique em Detalhes, e visualize a layout da tela e toda a sua coloração.

**Script**
`INSERT INTO PESSOA VALUES (1,12345678912,"Mulher Maravilha","M","49530000","Rua das Flores","Centro",
						   "Ribeirópolis","SE",null,"Sem telefone",null,"ms_danniel@outlook.com",null,null,
                           null,1,0,1,2,3);
                           
INSERT INTO PESSOA VALUES (10,96074947503,"Super Man","M","49530000","Rua das Flores","Centro",
						   "Ribeirópolis","SE",null,"Sem telefone",null,"ms_danniel@outlook.com",null,null,
                           null,1,0,1,2,3);
                           
INSERT INTO grupomusical VALUES(5, "Batalá - SE", "Batala Group", "22884507000195", "45565000",
                                "Travessa dos Imigrantes","Buritis", "Boa Vista", "RR" , "Brasil",
                                "batalateste@gmail.com", "/batalaRR", "@batalaRR", "/batalaRR", "(27) 2463-7172",
                                "(82) 2399-2069", "do Brasiiiil", "9999", "1739306-5", "394.464.570-76",  "CPF");
                                
INSERT INTO ensaio VALUES(9, 5, "FIXO", "120820230530", "120820230730", 1, "Ginásio", "Deprê", 1, 10);`

## Prints
**Observação:** caso a resolução da sua tela seja menor que 1400px, por favor, inspecione a tela e verifique como ela fica ao utrapassar esta faixa de valor. 

**Resolução menor que 1400px**
![image](https://github.com/marcosdosea/GestaoGrupoMusical/assets/62863349/413fdb59-d304-4e4d-9b9f-35b099b7bf72)
![image](https://github.com/marcosdosea/GestaoGrupoMusical/assets/62863349/0d0ba630-8b82-4793-9324-468c0ccecbf1)

**Resolução maior ou igual 1400px**
![image](https://github.com/marcosdosea/GestaoGrupoMusical/assets/62863349/91adac71-807a-4352-925f-a3be3d864fce)

**Certifique-se de revisar o código e testar as alterações localmente antes de solicitar/fazer o merge.**

2023-08-14 23:26 UTC, reinan47 requested changes
![image](https://github.com/marcosdosea/GestaoGrupoMusical/assets/91684220/849c712a-f0c7-4358-a22c-c51060eb47a8)
Deve segui o padrão da edit e o repertorio é do tipo textarea

2023-08-15 22:09 UTC, Gabrielx47 commented
O campo Repertório já é textarea.

2023-08-16 01:37 UTC, reinan47 requested changes
Atualize os prints da pr

2023-08-16 23:29 UTC, reinan47 approved these changes
Parabéns garelax

2023-08-16 23:29 UTC, merged