Delete Estoque - Figurino
marcosdosea/GestaoGrupoMusical pull request #401
Opened 2023-08-14 15:42 UTC by Gabrielx47

<div align="center">
  <img src="https://github.com/marcosdosea/GestaoGrupoMusical/assets/62726040/26118ce6-8a10-4f3a-b8a3-c3b90851b04b" width="10%">
  <h1>Pull Request</h1> 
</div>

## Foi Solicitado
A finalidade é habilitar o funcionamento do Delete de Estoque.

## Foi Feito
- [x] Criação de um modal para a o Delete de Estoque.
- [x] Criação do método DeleteEstoque no projeto Service.
- [x] Criação do método post DeleteEstoque na controller de figurino.
- [x] Implementação das notificações associadas a remoção de um estoque.

## Mudanças Que Não Estavam Previstas

## Como Testar
**Obsercação:** use o script abaixo para inserir dados no sistema.
Faça login no sistema como Administrador do Grupo. Em seguida, clique no menu e selecione a opção Figurinos. Após isso, escolha um dos figurinos e pressione o botão Estoque. Escolha um dos estoques e clique em Excluir.

**Script para inserir dados**
'''sql
INSERT INTO PESSOA VALUES (1,12345678912,"Mulher Maravilha","M","49530000","Rua das Flores","Centro",
						   "Ribeirópolis","SE",null,"Sem telefone",null,"ms_danniel@outlook.com",null,null,
                           null,1,0,1,2,3);
                           
INSERT INTO PESSOA VALUES (10,96074947503,"Super Man","M","49530000","Rua das Flores","Centro",
						   "Ribeirópolis","SE",null,"Sem telefone",null,"ms_danniel@outlook.com",null,null,
                           null,1,0,1,2,3);
                           
INSERT INTO grupomusical VALUES(5, "Batalá - SE", "Batala Group", "22884507000195", "45565000",
                                "Travessa dos Imigrantes","Buritis", "Boa Vista", "RR" , "Brasil",
                                "batalateste@gmail.com", "/batalaRR", "@batalaRR", "/batalaRR", "(27) 2463-7172",
                                "(82) 2399-2069", "do Brasiiiil", "9999", "1739306-5", "394.464.570-76",  "CPF");

INSERT INTO MANEQUIM VALUES (1,"PP","Extra Pequeno"),
							(2,"P","Pequeno"),
                            (3,"M","MEDIO"),
                            (4,"G","Grande");
                            
INSERT INTO figurino VALUES (2, "Galinha Pintadinha", "2023-08-14", 5),
							(3, "Mickey Mouse", "2023-08-14", 5);	
                            
insert INTO figurinomanequim VALUES (2, 3, 10, 0),
									(2, 4, 7, 0),
                                    (3, 1, 3, 0),
                                    (3, 2, 6, 0);
'''

## Prints
![image](https://github.com/marcosdosea/GestaoGrupoMusical/assets/62863349/43bdeb74-bedf-4611-9032-e82c5034edd0)

**Certifique-se de revisar o código e testar as alterações localmente antes de solicitar/fazer o merge.**

2023-08-15 13:42 UTC, ms-daniel requested changes

2023-08-15 13:42 UTC, ms-daniel commented on Codigo/GestaoGrupoMusicalWeb/GestaoGrupoMusicalWeb.csproj
remover este arquivos dos commits. (reverter)

2023-08-15 13:42 UTC, ms-daniel commented on Codigo/GestaoGrupoMusicalWeb/Views/Figurino/_TabelaEstoque.cshtml
> +                <form id="@(item.IdFigurino + item.IdManequim + "_confirmar")" asp-action="DeleteEstoque" asp-route-idFigurino="@item.IdFigurino" asp-route-idManequim="@item.IdManequim" method="post"
o form deve  ter apenas o botao de Excluir nele

2023-08-15 13:42 UTC, ms-daniel commented on Codigo/Service/FigurinoService.cs
> +        public async Task<int> DeleteEstoque(int idFigurino, int idManequim)
Usar FindAsync e não remover o estoque quando houver alguma peça emprestada.

2023-08-16 00:46 UTC, Gabrielx47 commented on Codigo/GestaoGrupoMusicalWeb/GestaoGrupoMusicalWeb.csproj
A única diferença é a versão. A main usa a 14 e a minha branch usa a 16. Sendo assim, mudei a versão para que ambas fiquem compatíveis.

2023-08-16 01:14 UTC, Gabrielx47 commented on Codigo/Service/FigurinoService.cs
> +        public async Task<int> DeleteEstoque(int idFigurino, int idManequim)
Feito.

2023-08-16 14:27 UTC, ms-daniel requested changes

2023-08-16 14:27 UTC, ms-daniel commented on Codigo/GestaoGrupoMusicalWeb/Controllers/FigurinoController.cs
> +using MySqlX.XDevAPI.Common;
remover esse namespace sem uso

2023-08-16 14:27 UTC, ms-daniel commented on Codigo/Service/FigurinoService.cs
> +                if (estoque.QuantidadeEntregue > 0)
A ideia é, ao excluir um estoque com peças entregues, o sistema zere a quantidade disponivel e surja uma notificação de alerta avisando a operação.

2023-08-18 16:12 UTC, Gabrielx47 commented on Codigo/Service/FigurinoService.cs
> +                if (estoque.QuantidadeEntregue > 0)
Então, não é para apagar o Estoque, apenas zerá-lo, né?

2023-08-18 17:33 UTC, ms-daniel commented on Codigo/Service/FigurinoService.cs
> +                if (estoque.QuantidadeEntregue > 0)
Apagar apenas quando nao houver peças emprestadas, quando houver basta zerar o estoque

2023-08-18 18:24 UTC, Gabrielx47 commented on Codigo/Service/FigurinoService.cs
> +                if (estoque.QuantidadeEntregue > 0)
Beleza, guerreiro!

2023-08-18 18:55 UTC, Gabrielx47 commented on Codigo/Service/FigurinoService.cs
> +                if (estoque.QuantidadeEntregue > 0)
Pronto.

2023-08-18 22:59 UTC, ms-daniel approved these changes
show!

2023-08-18 22:59 UTC, merged