Index - Figurinos - Design System
marcosdosea/GestaoGrupoMusical pull request #405
Opened 2023-08-14 23:13 UTC by Gabrielx47

<div align="center">
  <img src="https://github.com/marcosdosea/GestaoGrupoMusical/assets/62726040/26118ce6-8a10-4f3a-b8a3-c3b90851b04b" width="10%">
  <h1>Pull Request</h1> 
</div>

## Foi Solicitado
Colocar a view Index de Figurino nos padrões do design system do projeto Batalá.

## Foi Feito
- [x] Padronização do estilo da Index de Figurino.

## Mudanças Que Não Estavam Previstas

## Como Testar
Faça login no sistema como Administrador do sistema. Após isso, clique no menu e selecione a opção Figurinos. 

## Prints
![image](https://github.com/marcosdosea/GestaoGrupoMusical/assets/62863349/de2905dc-bde6-4d6c-bdd3-3916e615e900)

**Certifique-se de revisar o código e testar as alterações localmente antes de solicitar/fazer o merge.**

2023-08-14 23:34 UTC, reinan47 commented on Codigo/GestaoGrupoMusicalWeb/Views/Figurino/Index.cshtml
Mudar o titulo da index para o tamanho adequado.
<`h5`>@ViewData["Title"]<`/h5`>

2023-08-14 23:34 UTC, reinan47 requested changes
Verifique o comentário que fiz e mude o tamanho do titulo da index

2023-08-16 01:27 UTC, Gabrielx47 commented on Codigo/GestaoGrupoMusicalWeb/Views/Figurino/Index.cshtml
Feito!

2023-08-16 01:35 UTC, reinan47 approved these changes
Parabéns Garelax!

2023-08-16 01:35 UTC, merged