Feito o scaffolding da atualização do banco
marcosdosea/GestaoGrupoMusical pull request #441
Opened 2023-08-22 15:27 UTC by matheusmt12

<div align="center">
  <img src="https://github.com/marcosdosea/GestaoGrupoMusical/assets/62726040/26118ce6-8a10-4f3a-b8a3-c3b90851b04b" width="10%">
  <h1>Pull Request</h1> 
</div>

## Foi Solicitado
Atualizar o projeto com a atualização do banco de dados 

## Foi Feito
- [x] Scaffolding 

**Certifique-se de revisar o código e testar as alterações localmente antes de solicitar/fazer o merge.**

2023-08-22 16:57 UTC, lauro-ss requested changes
@matheusmt12 , houve novas mudanças, por favor faça novamente o scafolding

2023-08-22 17:46 UTC, junio10 commented
já atualizou ? @matheusmt12

2023-08-22 18:04 UTC, junio10 commented on Codigo/Core/GrupoMusicalContext.cs
>  #warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to re
@matheusmt12 comentem essa linha do context

2023-08-23 02:34 UTC, lauro-ss approved these changes

2023-08-23 02:35 UTC, merged