Adicionando funcionalidade para quantidade de figurinos que podem ser emprestados
marcosdosea/GestaoGrupoMusical pull request #462
Opened 2023-08-29 14:53 UTC by matheusmt12

<div align="center">
  <img src="https://github.com/marcosdosea/GestaoGrupoMusical/assets/62726040/26118ce6-8a10-4f3a-b8a3-c3b90851b04b" width="10%">
  <h1>Pull Request</h1> 
</div>

## Foi Solicitado
Adicionar funcionalidade para emprestar uma certa quantidade de figurino 

## Foi Feito
[Explique as alterações realizadas neste Pull Request de forma detalhada. Use o checklist markdown como o exemplo abaixo]
- [x] Alteração no método que busca a confirmação 

## Como Testar
Ter pelo menos 3 associados cadastrados no sistema, com acesso para confirmar que recebeu o figurino, ou vc pode confirmar diretamente pelo MySQL se quiser. Tendo isso, você poderá fazer movimentações entre eles.
(OBS: se você já emprestou um figurino para um associado e pretende emprestar outro para ele sem que ele tenha devolvido os outros que ele pegou, vai da erro. e em questão de retorno de notificação eu n coloquei deixei uma que já estava lá, como vamos mudar para o padrão sugerido. )

**Certifique-se de revisar o código e testar as alterações localmente antes de solicitar/fazer o merge.**

2023-08-29 22:55 UTC, ms-daniel commented
revisando

2023-08-29 23:26 UTC, ms-daniel requested changes
# Correções
- [ ] Veja os comentários nos arquivos
- [ ] não criar uma nova movimentação para recebido ao devolver peças com numero menor do que o de emprestado
- [ ] adicionar quantidade de peças emprestadas na view do associado

2023-08-29 23:26 UTC, ms-daniel commented on Codigo/Service/MovimentacaoFigurinoService.cs
> +                    if (movimentacao.Quantidade <= 0 || movimentacao.Quantidade >
duas condições estão quase iguais

2023-08-29 23:26 UTC, ms-daniel commented on Codigo/Service/MovimentacaoFigurinoService.cs
> +                            return 403; //não ouve confirmação
"houve"

2023-08-29 23:26 UTC, ms-daniel commented on Codigo/Service/MovimentacaoFigurinoService.cs
> +                        if (movimentacao.Quantidade <= 0 || movimentacao.Quantidade > confiQuantAssociado.Quantidade)
colocar em estrutura if else pra melhorar desempenho

2023-08-30 18:53 UTC, ms-daniel requested changes
resolver conflitos

2023-08-30 20:53 UTC, matheusmt12 commented
Conflitos resolvidos, sugiro que revise novamente

2023-08-30 23:01 UTC, ms-daniel requested changes

2023-08-30 23:01 UTC, ms-daniel commented on Codigo/GestaoGrupoMusicalWeb/Views/Figurino/_TabelaMovimentacao.cshtml
Quebrou uma funcionalidade da <a href="https://github.com/marcosdosea/GestaoGrupoMusical/pull/464">PR 464</a>

2023-08-30 23:48 UTC, matheusmt12 commented on Codigo/GestaoGrupoMusicalWeb/Views/Figurino/_TabelaMovimentacao.cshtml
Concertei, veja novamente por favor

2023-08-31 17:14 UTC, ms-daniel requested changes
adicionar quantidade a tabela do associado.
![image](https://github.com/marcosdosea/GestaoGrupoMusical/assets/62726040/24519789-abdc-4061-82a2-ffa67cb0fb6e)

2023-08-31 20:44 UTC, matheusmt12 commented
Tá na mão:
![Captura de tela 2023-08-31 174326](https://github.com/marcosdosea/GestaoGrupoMusical/assets/82002419/a927b775-48bf-4f20-8db7-3459fc29cc44)

2023-09-01 12:13 UTC, ms-daniel approved these changes
Parabéns!

2023-09-01 12:14 UTC, merged