Branch reinan432
marcosdosea/GestaoGrupoMusical pull request #468
Opened 2023-08-30 02:02 UTC by reinan47

<div align="center">
  <img src="https://github.com/marcosdosea/GestaoGrupoMusical/assets/62726040/26118ce6-8a10-4f3a-b8a3-c3b90851b04b" width="10%">
  <h1>Pull Request</h1> 
</div>

## Foi Solicitado
A adição de paginação para a view index de associado
## Foi Feito
- [x] A modificação da PessoaController para se adaptar ao X.pagedList.MVC.Core 
- [x] Modificações na index de pessoa para adicionar a paginação.
- [x] Adição de link para ordenação nas colunas `Nome` e `Ativo` 
- [x] Estilização da page-item;
- [x] Adição de um icon onde fica alternando de acordo com a ordenação `Crecente` ou `Decrescente`  

## Como Testar
Ir na view index de associado e verificar as ordenações clicando na coluna `Nome` ou `Ativo` 

**Certifique-se de revisar o código e testar as alterações localmente antes de solicitar/fazer o merge.**

2023-09-05 16:10 UTC, lauro-ss commented
@reinan47 sua PR está com conflitos, resolva e assim irei revisar

2023-09-06 20:14 UTC, lauro-ss commented
revisando

2023-09-06 21:07 UTC, lauro-ss requested changes
@reinan47 o método GetAllAssociadoDTOByGroup() consulta todos os registros e depois pagina, você precisa encontrar alguma maneira de que ele consulte apenas os resultados desejados. Você pode utilizar o .ToPagedListAsync ou .ToPagedList na query ou utilizar .Take() e o .Skip()

2023-09-12 01:07 UTC, reinan47 commented
Remorção do pagedList

2023-09-12 01:07 UTC, closed without merging