Descartar Figurino - Funcionalidade - Movimentar Figurino
marcosdosea/GestaoGrupoMusical pull request #487
Opened 2023-09-05 08:29 UTC by Gabrielx47

<div align="center">
  <img src="https://github.com/marcosdosea/GestaoGrupoMusical/assets/62726040/26118ce6-8a10-4f3a-b8a3-c3b90851b04b" width="10%">
  <h1>Pull Request</h1> 
</div>

## Foi Solicitado
Construção de uma funcionalidade capaz de descartar figurinos.

## Foi Feito
- [x] Alteração no método CreateAsync (Service);
- [x] Alteração do arquivo "Movimentar.cshtml" para implamantar a opção de descarte. 
- [x] Ao selecionar a opção "Descartar" o campo Associado é desabilitado, pois o associado ao descarte é quem o faz.
- [x] Na tabela de movimentações, as que possuem status de danificada não possui o botão de "Notificar".   

## Mudanças Que Não Estavam Previstas
- [x] O retorno dos métodos da service de movimentar figurino usam código de status do http. 
- [x] Definição de faixa de valores para o campo Quantidade. 
- [ ] Item 3

## Como Testar
Cria um figurino -> Cria Estoque de Figurino -> Descarta o estoque de figurinos (Observação: tentar descartar uma quantidade maior do que a disponível; tentar descartar uma quantidade zero de figurinos).

## Prints
![image](https://github.com/marcosdosea/GestaoGrupoMusical/assets/62863349/2130a1f9-c17b-4974-8d9b-74700a652e11)
![image](https://github.com/marcosdosea/GestaoGrupoMusical/assets/62863349/d9385f32-db52-47f9-9370-ff0b6b518248)

**Certifique-se de revisar o código e testar as alterações localmente antes de solicitar/fazer o merge.**

2023-09-06 15:15 UTC, ms-daniel requested changes
resolver conflitos

2023-09-10 17:32 UTC, ms-daniel requested changes
remover nome do associado do list ao selecionar descarte para não dar ideia de que o descarte estará associado aquele associado

2023-09-10 17:32 UTC, ms-daniel commented on Codigo/GestaoGrupoMusicalWeb/Controllers/FigurinoController.cs
>  namespace GestaoGrupoMusicalWeb.Controllers
remover namespace redundante

2023-09-13 16:54 UTC, ms-daniel submitted a review, later dismissed
Além dos comentários nos arquivos: o input para o nome do associado está sumindo, ao inves de fazer o input sumir coloque o nome do colaborador no input.

2023-09-13 16:54 UTC, ms-daniel commented on Codigo/GestaoGrupoMusicalWeb/Controllers/FigurinoController.cs
> +                Movimentacaofigurino movimentacao = new Movimentacaofigurino
remover tab para ajustar indentação

2023-09-13 16:54 UTC, ms-daniel commented on Codigo/GestaoGrupoMusicalWeb/Views/Figurino/Movimentar.cshtml
> +            <div class="col-lg-6" id="associado" >
aitrbuir um nome mais apropriado para o id desta div

2023-09-18 17:43 UTC, junio10 commented
revisando !

2023-09-18 18:46 UTC, junio10 approved these changes
parabéns @Gabrielx47

2023-09-18 18:47 UTC, merged