Branch moises495
marcosdosea/GestaoGrupoMusical pull request #504
Opened 2023-09-11 18:51 UTC by junio10

<div align="center">
  <img src="https://github.com/marcosdosea/GestaoGrupoMusical/assets/62726040/26118ce6-8a10-4f3a-b8a3-c3b90851b04b" width="10%">
  <h1>Pull Request</h1> 
</div>

## Foi Solicitado
Alterar retorno de Index Ensaio e voltar a exibir tela de início como do protótipo

## Foi Feito
[Explique as alterações realizadas neste Pull Request de forma detalhada. Use o checklist markdown como o exemplo abaixo]
- [x] Mudança no retorno de tela index
- [x] Comentar parte do código da view informativo, que não será entregue
- [x] Adicionado botão para evento na index Adm Grupo musical

## Como Testar
-Entrar como adm do grupo musical, e demais roles. Verificar se a tela retornada corresponde ao papel

## Prints
![image](https://github.com/marcosdosea/GestaoGrupoMusical/assets/50469065/68081ca8-f6dd-4cea-9d90-9d32630c3f6d)

**Certifique-se de revisar o código e testar as alterações localmente antes de solicitar/fazer o merge.**

2023-09-11 21:32 UTC, junio10 commented
ninguém aprove, irei fazer uma mudança

2023-09-12 17:44 UTC, junio10 commented
Mudanças realizadas, como as funções dos protótipos não estão concluidas, não deu pra deixar igual: que são informativos e eventos que não estão concluídas. Como das funcionalidades pronta da index principal, só tinha ensaio, deixe sendo a tela de ensaio. Para adm grupo musical

2023-09-12 20:13 UTC, lauro-ss requested changes
@junio10 no método Index da Controller Home, o retorno deve ser o return View(viewModel); a ideia é voltar a exibir a tela de início antiga e não mais redirecionar o Adm Grupo para a tela de instrumento

2023-09-13 14:54 UTC, junio10 commented
> @junio10 no método Index da Controller Home, o retorno deve ser o return View(viewModel); a ideia é voltar a exibir a tela de início antiga e não mais redirecionar o Adm Grupo para a tela de instrumento. Do jeito que estar, ao acessar ou ao clicar no link início ele continua redirecionando o Adm Grupo para a tela de instrumento

2023-09-13 14:57 UTC, junio10 commented
Está redirecionando para tela de ensaio, que é a única funcionalidade que está pronta do protótipo da index home. informativo e eventos não estão prontos, por isso não faz sentido redirecionar para essa home index

2023-09-13 22:50 UTC, lauro-ss approved these changes

2023-09-13 22:50 UTC, merged