Tradução dos textos da view: UC - Manter Associados
marcosdosea/GestaoGrupoMusical pull request #68
Opened 2023-06-16 10:09 UTC by Gabrielx47

## Revisar:
- Verificar se os textos de todas as views do "UC Manter Associados" estão traduzidas.

2023-06-16 18:13 UTC, junio10 approved these changes
Views traduzidas de associados.  resolve #52

2023-06-17 00:45 UTC, ms-daniel reviewed
Alterar a view Edit.cshtml para mostrar o nome Pessoa ao invés de associado, uma vez que associado é apenas um papel de uma pessoa

2023-06-17 00:47 UTC, ms-daniel requested changes

2023-06-17 00:47 UTC, ms-daniel commented on Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Edit.cshtml
Alterar nome Associado para Pessoa (termo genérico) ou colocar o nome da pessoa que esta editando

2023-06-17 00:47 UTC, ms-daniel commented on Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Details.cshtml
Alterar nome Associado para Pessoa (termo genérico) ou colocar o nome da pessoa que mostrando detalhes

2023-06-17 00:47 UTC, ms-daniel commented on Codigo/GestaoGrupoMusicalWeb/Views/Pessoa/Index.cshtml
Alterar nome Associado para Pessoa (termo genérico) junto ao "Novo"

2023-06-17 00:59 UTC, ms-daniel approved these changes

2023-06-17 00:59 UTC, merged